### PR TITLE
Readd link and fix typing-extensions pin

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@thewchan, any reason you deleted my link to the upstream `setup.py` in #17? Also a pin should have been added for `typing-extensions` in #17.

**Comment by thewchan** [comment]
Sorry I figure we dropped 3.6 support anyway so no need to include that but if you want to add it in that's up to you

**Comment by maresb** [comment]
Ah, it looks like you're referring to my subsequent comments. Those are basically a note-to-self that `dataclasses` and `backports-datetime-fromisoformat` are in `install_requires` but can be ignored since they are 3.6-only.

**Pull request merged**
