### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by maresb**
# This should be merged into a separate branch!

That's why I made this a draft pull request. I can't target a nonexistent branch.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@thewchan this is ready to go except for the branch

**Comment by thewchan** [comment]
I'll push a new empty branch to the repo and you can retarget it

**Comment by thewchan** [comment]
@maresb the v2.5 branch should exist now, you can retarget this PR to that branch instead

**Comment by maresb** [comment]
Thanks @thewchan! I don't see your branch, but no worries, I'll take care of it. I should anyway rebase on master now that I'm maintainer so that I don't accidentally remove myself! :D

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
This has already been pushed to the `v2.5` branch. I can't do a noop merge, so closing.

**Pull request closed without merging**
